services:
  postgres:
    image: postgres:15
    container_name: socialfeed_postgres
    restart: always
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: socialpass
      POSTGRES_DB: socialdb
    ports:
      - "5434:5432" # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
